In [538]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

# Seleccionen al azar 10 flores de cada categoría y usando la distancia euclidiana de la primera y cuarta columna calcular la sensibilidad, especificidad y precisión para k=3 y 5

## Lectura del documento y asignación de nombre a las columnas

In [539]:
data = pd.read_csv('color_iris.csv')

columnas = ['Sepal length','Sepal width','Petal length','Petal widht','Flower']
data.columns=columnas
data

     Sepal length  Sepal width  Petal length  Petal widht          Flower
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

### Se cambian los nombres de las flores por números para un mejor manejo de los datos

In [540]:
data['Flower'] = data['Flower'].replace('Iris-setosa',0)
data['Flower'] = data['Flower'].replace('Iris-versicolor',1)
data['Flower'] = data['Flower'].replace('Iris-virginica',2)
data

     Sepal length  Sepal width  Petal length  Petal widht  Flower
0             4.9          3.0           1.4          0.2       0
1             4.7          3.2           1.3          0.2       0
2             4.6          3.1           1.5          0.2       0
3             5.0          3.6           1.4          0.2       0
4             5.4          3.9           1.7          0.4       0
..            ...          ...           ...          ...     ...
144           6.7          3.0           5.2          2.3       2
145           6.3          2.5           5.0          1.9       2
146           6.5          3.0           5.2          2.0       2
147           6.2          3.4           5.4          2.3       2
148           5.9          3.0           5.1          1.8       2

[149 rows x 5 columns]

## Selección al azar de 10 flores de cada categoría

### Separación de la data según la categoría

In [541]:
data_setosa = data[:49]
data_versicolor = data[49:99]
data_virginica = data[99:]

### Mezcla de la data para la selección al azar de 10 flores

In [542]:
#Iris-setosa
data_setosa = data_setosa.to_numpy()
np.random.shuffle(data_setosa)
data_setosa = pd.DataFrame(data_setosa)
data_setosa.columns=columnas
#Iris-versicolor
data_versicolor = data_versicolor.to_numpy()
np.random.shuffle(data_versicolor)
data_versicolor = pd.DataFrame(data_versicolor)
data_versicolor.columns=columnas
#Iris-virginica
data_virginica = data_virginica.to_numpy()
np.random.shuffle(data_virginica)
data_virginica = pd.DataFrame(data_virginica)
data_virginica.columns=columnas

### Selección de 10 flores

In [543]:
flores=pd.DataFrame
flores = pd.concat([data_setosa[:10],data_versicolor[:10],data_virginica[:10]])
flores

   Sepal length  Sepal width  Petal length  Petal widht  Flower
0           4.6          3.2           1.4          0.2     0.0
1           4.9          3.1           1.5          0.1     0.0
2           5.0          3.3           1.4          0.2     0.0
3           5.1          3.8           1.6          0.2     0.0
4           5.0          3.2           1.2          0.2     0.0
5           5.0          3.5           1.6          0.6     0.0
6           5.1          3.8           1.5          0.3     0.0
7           4.7          3.2           1.3          0.2     0.0
8           4.8          3.0           1.4          0.1     0.0
9           5.0          3.4           1.5          0.2     0.0
0           6.3          3.3           4.7          1.6     1.0
1           6.3          2.3           4.4          1.3     1.0
2           5.6          2.5           3.9          1.1     1.0
3           6.7          3.1           4.4          1.4     1.0
4           6.3          2.5           4.9          1.5     1.0
5           6.9          3.1           4.9          1.5     1.0
6           5.7          2.8           4.5          1.3     1.0
7           5.6          3.0           4.5          1.5     1.0
8           6.4          2.9           4.3          1.3     1.0
9           5.1          2.5           3.0          1.1     1.0
0           6.9          3.1           5.4          2.1     2.0
1           7.7          2.8           6.7          2.0     2.0
2           6.7          3.1           5.6          2.4     2.0
3           7.1          3.0           5.9          2.1     2.0
4           6.0          2.2           5.0          1.5     2.0
5           7.2          3.0           5.8          1.6     2.0
6           6.1          2.6           5.6          1.4     2.0
7           6.4          3.1           5.5          1.8     2.0
8           6.8          3.2           5.9          2.3     2.0
9           6.3          2.5           5.0          1.9     2.0

### Mezcla de las flores seleccionadas

In [544]:
flores = flores.to_numpy()
np.random.shuffle(flores)
flores = pd.DataFrame(flores)
flores.columns=columnas

## Calcular la sensibilidad, especificidad y precisión para k=3 y 5 usando la distancia euclidiana

### Se define una función para calcular la distancia euclidiana

In [545]:
def euclidiana(test,train):
  distancia = 0
  for i in range(len(test)):
      distancia += (test[i] - train[i]) ** 2
  return math.sqrt(distancia)

### Se define una función para obtener los k vecinos más cercanos

In [546]:
def prediccion(X_train, y_train, X_test, k):
    # Lista para guardar las predicciones
    y_pred = []
    for i in range(len(X_test)):
      # Lista para guardar todas las distancias calculadas
        distancias = []
        for j in range(len(X_train)):
            distancia = euclidiana(X_test[i], X_train[j]) # Se calcula la distancia euclidiana
            distancias.append((distancia, y_train[j])) # Se agrega la distancia calculada
        distancias.sort() # Se ordena la lista de las distancias
        vecinos = distancias[:k] # Se sacan las k distancias más cortas
        cont = {}
        for vecino in vecinos: # Se realiza la votación para hacer la predicción
            if vecino[1] in cont:
                cont[vecino[1]] += 1
            else:
                cont[vecino[1]] = 1
        y_pred.append(max(cont, key=cont.get)) # Se agrega la predicción a la lista de predicciones
    return y_pred

### Se define una función para calcular sensibilidad, especificidad y precision

In [547]:
def matriz(y_test,y_pred):
  true_positives = [0, 0, 0]
  false_negatives = [0, 0, 0]
  true_negatives = [0, 0, 0]
  false_positives = [0, 0, 0]

  for i in range(len(y_test)):
    for j in range(3):
      if y_pred[i]==j and y_test[i]==j:
        true_positives[j] += 1
      elif y_pred[i]!=j and y_test[i]==j:
        false_negatives[j] += 1
      elif y_pred[i]!=j and y_test[i]!=j:
        true_negatives[j] += 1
      elif y_pred[i]==j and y_test[i]!=j:
        false_positives[j] += 1

  confusion = pd.DataFrame({
      "Flor":["Iris-setosa","Iris-versicolor","Iris-virginica"],
      "True positives": true_positives,
      "False negatives":false_negatives,
      "False positives":false_positives,
      "True negatives":true_negatives
  })
  # Cálculo de sensibilidad
  sensitivity_setosa = confusion.iloc[0][1] / (confusion.iloc[0][1] + confusion.iloc[0][2])
  sensitivity_versicolor = confusion.iloc[1][1] / (confusion.iloc[1][1] + confusion.iloc[1][2])
  sensitivity_virginica = confusion.iloc[2][1] / (confusion.iloc[2][1] + confusion.iloc[2][2])
  sensitivity = [sensitivity_setosa,sensitivity_versicolor,sensitivity_virginica]
  confusion["Sensitivity"] = sensitivity
  # Calculo de especificidad
  specificity_setosa = confusion.iloc[0][4] / (confusion.iloc[0][4] + confusion.iloc[0][3])
  specificity_versicolor = confusion.iloc[1][4] / (confusion.iloc[1][4] + confusion.iloc[1][3])
  specificity_virginica = confusion.iloc[2][4] / (confusion.iloc[2][4] + confusion.iloc[2][3])
  specificity = [specificity_setosa,specificity_versicolor,specificity_virginica]
  confusion["Specificity"] = specificity
  #Calculo de precision
  precision_setosa = confusion.iloc[0][1] / (confusion.iloc[0][1] + confusion.iloc[0][3])
  precision_versicolor = confusion.iloc[1][1] / (confusion.iloc[1][1] + confusion.iloc[1][3])
  precision_virginica = confusion.iloc[2][1] / (confusion.iloc[2][1] + confusion.iloc[2][3])
  precision = [precision_setosa,precision_versicolor,precision_virginica]
  confusion["Precision"] = precision
  confusion.fillna(0)
  return confusion

### Separación del dataframe para realizar las predicciones

In [548]:
# Se trabajó con una relación 80-20
data_train = flores[:24]
data_test = flores[24:]
# Asignación de los datos para generar el KNN
x_train = data_train.iloc[:,[0,3]].values
y_train = data_train.iloc[:,4].values
# Asignación de los datos para probar el modelo
x_test = data_test.iloc[:,[0,3]].values
y_test = data_test.iloc[:,4].values

### K = 3

In [549]:
k=3
y_pred=prediccion(x_train,y_train,x_test,k)
print(y_test)
print(y_pred)

[2. 1. 2. 1. 1. 0.]
[2.0, 0.0, 2.0, 2.0, 2.0, 0.0]

### Tabla con TP, FN, FP, TN, sensibilidad, especificidad y precisión para cada flor

In [550]:
tabla = matriz(y_test,y_pred)
tabla

<ipython-input-547-555a5b9b8679>:39: RuntimeWarning: invalid value encountered in long_scalars
  precision_versicolor = confusion.iloc[1][1] / (confusion.iloc[1][1] + confusion.iloc[1][3])

,Flor,True positives,False negatives,False positives,True negatives,Sensitivity,Specificity,Precision
0,Iris-setosa,1,0,1,4,1.0,0.8,0.5
1,Iris-versicolor,0,3,0,3,0.0,1.0,NaN
2,Iris-virginica,2,0,2,2,1.0,0.5,0.5

### K = 5

In [551]:
k=5
y_pred=prediccion(x_train,y_train,x_test,k)
print(y_test)
print(y_pred)

[2. 1. 2. 1. 1. 0.]
[2.0, 0.0, 2.0, 1.0, 1.0, 0.0]

### Tabla con TP, FN, FP, TN, sensibilidad, especificidad y precisión para cada flor

In [552]:
tabla = matriz(y_test,y_pred)
tabla

,Flor,True positives,False negatives,False positives,True negatives,Sensitivity,Specificity,Precision
0,Iris-setosa,1,0,1,4,1.000000,0.8,0.5
1,Iris-versicolor,2,1,0,3,0.666667,1.0,1.0
2,Iris-virginica,2,0,0,4,1.000000,1.0,1.0